apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: spring-svc
    job: app1-job
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: drissjabri/app1
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
